/// register user
export const REGISTER_CREATE_REQUEST = 'REGISTER_CREATE_REQUEST';
export const REGISTER_CREATE_SUCCESS = 'REGISTER_CREATE_SUCCESS'
export const REGISTER_CREATE_FAIL = 'REGISTER_CREATE_FAIL'

//update admin profile
export const UPDATE_ADMIN_PROFILE_REQUEST = 'UPDATE_ADMIN_PROFILE_REQUEST';
export const UPDATE_ADMIN_PROFILE_SUCCESS = 'UPDATE_ADMIN_PROFILE_SUCCESS';
export const UPDATE_ADMIN_PROFILE_FAIL = 'UPDATE_ADMIN_PROFILE_FAIL';

///update admin email
export const UPDATE_ADMIN_EMAIL_REQUEST = 'UPDATE_ADMIN_EMAIL_REQUEST';
export const UPDATE_ADMIN_EMAIL_SUCCESS = 'UPDATE_ADMIN_EMAIL_SUCCESS';
export const UPDATE_ADMIN_EMAIL_FAIL = 'UPDATE_ADMIN_EMAIL_FAIL';

export const UPDATE_ADMIN_EMAIL_OTP_REQUEST = 'UPDATE_ADMIN_EMAIL_OTP_REQUEST';
export const UPDATE_ADMIN_EMAIL_OTP_SUCCESS = 'UPDATE_ADMIN_EMAIL_OTP_SUCCESS';
export const UPDATE_ADMIN_EMAIL_OTP_FAIL = 'UPDATE_ADMIN_EMAIL_OTP_FAIL';

///update admin password
export const UPDATE_ADMIN_PASSWORD_REQUEST = 'UPDATE_ADMIN_PASSWORD_REQUEST';
export const UPDATE_ADMIN_PASSWORD_SUCCESS = 'UPDATE_ADMIN_PASSWORD_SUCCESS';
export const UPDATE_ADMIN_PASSWORD_FAIL = 'UPDATE_ADMIN_PASSWORD_FAIL';

/// login user
export const LOGIN_CREATE_REQUEST = 'LOGIN_CREATE_REQUEST';
export const LOGIN_CREATE_SUCCESS = 'LOGIN_CREATE_SUCCESS';
export const LOGIN_CREATE_FAIL = 'LOGIN_CREATE_FAIL';

/// delete admin
export const DELETE_ADMIN_REQUEST = 'DELETE_ADMIN_REQUEST';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';
export const DELETE_ADMIN_FAIL = 'DELETE_ADMIN_FAIL';

///otp send for register user
export const OTP_SEND_REQUEST = 'OTP_SEND_REQUEST';
export const OTP_SEND_SUCCESS = 'OTP_SEND_SUCCESS';
export const OTP_SEND_FAIL = 'OTP_SEND_FAIL';

//forget password otp send
export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL';

///forget password confirm
export const FORGET_PASSWORD_CONFIRM_REQUEST = 'FORGET_PASSWORD_CONFIRM_REQUEST';
export const FORGET_PASSWORD_CONFIRM_SUCCESS = 'FORGET_PASSWORD_CONFIRM_SUCCESS';
export const FORGET_PASSWORD_CONFIRM_FAIL = 'FORGET_PASSWORD_CONFIRM_FAIL';

///refresh user token
export const USER_TOKEN_REFRESH_REQUEST = 'USER_TOKEN_REFRESH_REQUEST';
export const USER_TOKEN_REFRESH_SUCCESS = 'USER_TOKEN_REFRESH_SUCCESS';
export const USER_TOKEN_REFRESH_FAIL = 'USER_TOKEN_REFRESH_FAIL';

///logout user
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';

//refresh user reducers
export const REFRESH_LODDER_AUTH = 'REFRESH_LODDER_AUTH';

/// get all admin lists
export const GET_ALL_ADMIN_LISTS_REQUEST = 'GET_ALL_ADMIN_LISTS_REQUEST';
export const GET_ALL_ADMIN_LISTS_SUCCESS = 'GET_ALL_ADMIN_LISTS_SUCCESS';
export const GET_ALL_ADMIN_LISTS_FAIL = 'GET_ALL_ADMIN_LISTS_FAIL';

///get all permission
export const GET_ALL_PERMISSION_LISTS_REQUEST = 'GET_ALL_PERMISSION_LISTS_REQUEST';
export const GET_ALL_PERMISSION_LISTS_SUCCESS = 'GET_ALL_PERMISSION_LISTS_SUCCESS';
export const GET_ALL_PERMISSION_LISTS_FAIL = 'GET_ALL_PERMISSION_LISTS_FAIL';

///create permission
export const CREATE_ADMIN_ROLE_REQUEST = 'CREATE_ADMIN_ROLE_REQUEST';
export const CREATE_ADMIN_ROLE_SUCCESS = 'CREATE_ADMIN_ROLE_SUCCESS';
export const CREATE_ADMIN_ROLE_FAIL = 'CREATE_ADMIN_ROLE_FAIL';

///get all role lists
export const GET_ALL_ROLE_LISTS_REQUEST = 'GET_ALL_ROLE_LISTS_REQUEST';
export const GET_ALL_ROLE_LISTS_SUCCESS = 'GET_ALL_ROLE_LISTS_SUCCESS';
export const GET_ALL_ROLE_LISTS_FAIL = 'GET_ALL_ROLE_LISTS_FAIL';

///given permissions
export const GIVEN_ROLE_PERMISSION_TO_ADMIN_REQUEST = 'GIVEN_ROLE_PERMISSION_TO_ADMIN_REQUEST';
export const GIVEN_ROLE_PERMISSION_TO_ADMIN_SUCCESS = 'GIVEN_ROLE_PERMISSION_TO_ADMIN_SUCCESS';
export const GIVEN_ROLE_PERMISSION_TO_ADMIN_FAIL = 'GIVEN_ROLE_PERMISSION_TO_ADMIN_FAIL';

///update admin role
export const UPDATE_ADMIN_ROLE_REQUEST = 'UPDATE_ADMIN_ROLE_REQUEST';
export const UPDATE_ADMIN_ROLE_SUCCESS = 'UPDATE_ADMIN_ROLE_SUCCESS';
export const UPDATE_ADMIN_ROLE_FAIL = 'UPDATE_ADMIN_ROLE_FAIL';

///delete admin role
export const DELETE_ADMIN_ROLE_REQUEST = 'DELETE_ADMIN_ROLE_REQUEST';
export const DELETE_ADMIN_ROLE_SUCCESS = 'DELETE_ADMIN_ROLE_SUCCESS';
export const DELETE_ADMIN_ROLE_FAIL = 'DELETE_ADMIN_ROLE_FAIL';