 export const SEND_GROUP_NOTIFICATION_REQUEST = 'SEND_GROUP_NOTIFICATION_REQUEST';
 export const SEND_GROUP_NOTIFICATION_SUCCESS = 'SEND_GROUP_NOTIFICATION_SUCCESS';
 export const SEND_GROUP_NOTIFICATION_FAIL = 'SEND_GROUP_NOTIFICATION_FAIL';


 export const REFRESH_NOTIFICATION_REQUEST = 'REFRESH_NOTIFICATION_REQUEST';


 export const SEND_SINGLE_NOTIFICATION_REQUEST = 'SEND_SINGLE_NOTIFICATION_REQUEST';
 export const SEND_SINGLE_NOTIFICATION_SUCCESS = 'SEND_SINGLE_NOTIFICATION_SUCCESS';
 export const SEND_SINGLE_NOTIFICATION_FAIL = 'SEND_SINGLE_NOTIFICATION_FAIL';


 export const GET_ALL_NOTIFICATION_REQUEST = 'GET_ALL_NOTIFICATION_REQUEST';
 export const  GET_ALL_NOTIFICATION_SUCCESS ='GET_ALL_NOTIFICATION_SUCCESS';
 export const GET_ALL_NOTIFICATION_FAIL = 'GET_ALL_NOTIFICATION_FAIL';


 export const GET_SINGLE_USER_NOTIFICATION_SUCCESS = 'GET_SINGLE_USER_NOTIFICATION_SUCCESS';
 export const GET_SINGLE_USER_NOTIFICATION_REQUEST = 'GET_SINGLE_USER_NOTIFICATION_REQUEST';
 export const GET_SINGLE_USER_NOTIFICATION_FAIL = 'GET_SINGLE_USER_NOTIFICATION_FAIL';


 export const DLELETE_NOTIFICATION_BY_ADMIN_REQUEST = 'DLELETE_NOTIFICATION_BY_ADMIN_REQUEST';
 export const DLELETE_NOTIFICATION_BY_ADMIN_SUCCESS = 'DLELETE_NOTIFICATION_BY_ADMIN_SUCCESS';
 export const DLELETE_NOTIFICATION_BY_ADMIN_FAIL = 'DLELETE_NOTIFICATION_BY_ADMIN_FAIL';

 export const DLELETE_NOTIFICATION_BY_USER_REQUEST = 'DLELETE_NOTIFICATION_BY_USER_REQUEST' ;
 export const DLELETE_NOTIFICATION_BY_USER_SUCCESS = 'DLELETE_NOTIFICATION_BY_USER_SUCCESS';
 export const DLELETE_NOTIFICATION_BY_USER_FAIL = 'DLELETE_NOTIFICATION_BY_USER_FAIL';

 export const UPDATE_NOTIFICATION_BY_ADMIN_REQUEST = 'UPDATE_NOTIFICATION_BY_ADMIN_REQUEST';
 export const UPDATE_NOTIFICATION_BY_ADMIN_SUCCESS = 'UPDATE_NOTIFICATION_BY_ADMIN_SUCCESS';
 export const UPDATE_NOTIFICATION_BY_ADMIN_FAIL = 'UPDATE_NOTIFICATION_BY_ADMIN_FAIL' ;