export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SING_UP_FAIL = 'USER_SING_UP_FAIL';

export const USER_SIGN_UP_OTP_REQUEST = 'USER_SIGN_UP_OTP_REQUEST';
export const USER_SIGN_UP_OTP_SUCCESS = 'USER_SIGN_UP_OTP_SUCCESS';
export const USER_SIGN_UP_OTP_FAIL = 'USER_SIGN_UP_OTP_FAIL';

export const USER_SING_IN_FAIL = 'USER_SING_IN_FAIL';
export const USER_SIGN_IN_REQUEST = 'USER_SIGN_IN_REQUEST';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';

export const REFRESH_CLIENT_REQUEST = 'REFRESH_CLIENT_REQUEST';

export const USER_OTP_COUNT_SUCCESS = 'USER_OTP_COUNT_SUCCESS';

export const USER_LOGOUT_REQUEST_SUCCESS = 'USER_LOGOUT_REQUEST_SUCCESS';

export const USER_FORGET_PASSWORD_REQUEST_REQUEST = 'USER_FORGET_PASSWORD_REQUEST_REQUEST';
export const USER_FORGET_PASSWORD_REQUEST_SUCCESS = 'USER_FORGET_PASSWORD_REQUEST_SUCCESS';
export const USER_FORGET_PASSWORD_REQUEST_FAIL = 'USER_FORGET_PASSWORD_REQUEST_FAIL';
export const USER_FORGET_PASSWORD_REQUEST_VALIDATE_REQUEST = 'USER_FORGET_PASSWORD_REQUEST_VALIDATE_REQUEST';
export const USER_FORGET_PASSWORD_REQUEST_VALIDATE_SUCCESS = 'USER_FORGET_PASSWORD_REQUEST_VALIDATE_SUCCESS';
export const USER_FORGET_PASSWORD_REQUEST_VALIDATE_FAIL = 'USER_FORGET_PASSWORD_REQUEST_VALIDATE_FAIL';

export const GET_CLIENT_PROFILE_SUCCESS = 'GET_CLIENT_PROFILE_SUCCESS';
export const GET_CLIENT_PROFILE_REQUEST = 'GET_CLIENT_PROFILE_REQUEST';
export const GET_CLIENT_PROFILE_FAIL = 'GET_CLIENT_PROFILE_FAIL';

export const UPDATE_CLIENT_PROFILE_REQUEST = 'UPDATE_CLIENT_PROFILE_REQUEST';
export const UPDATE_CLIENT_PROFILE_SUCCESS = 'UPDATE_CLIENT_PROFILE_SUCCESS';
export const UPDATE_CLIENT_PROFILE_FAIL = 'UPDATE_CLIENT_PROFILE_FAIL';

export const SEND_MESSAGE_CLIENT_TO_ADMIN_REQUEST = 'SEND_MESSAGE_CLIENT_TO_ADMIN_REQUEST';
export const SEND_MESSAGE_CLIENT_TO_ADMIN_SUCCESS = 'SEND_MESSAGE_CLIENT_TO_ADMIN_SUCCESS';
export const SEND_MESSAGE_CLIENT_TO_ADMIN_FAIL = 'SEND_MESSAGE_CLIENT_TO_ADMIN_FAIL';
export const REFRESH_CONTRACT_MESSAGE_REQURST  = 'REFRESH_CONTRACT_MESSAGE_REQURST';

export const FIND_SERVICE_TO_WORKERS_REQUEST = 'FIND_SERVICE_TO_WORKERS_REQUEST';
export const FIND_SERVICE_TO_WORKERS_SUCCESS = 'FIND_SERVICE_TO_WORKERS_SUCCESS';
export const FIND_SERVICE_TO_WORKERS_FAIL = 'FIND_SERVICE_TO_WORKERS_FAIL';
export const FIND_WORKERS_TO_SERVICES_REQUEST = 'FIND_WORKERS_TO_SERVICES_REQUEST';
export const FIND_WORKERS_TO_SERVICES_SUCCESS = 'FIND_WORKERS_TO_SERVICES_SUCCESS';
export const FIND_WORKERS_TO_SERVICES_FAIL = 'FIND_WORKERS_TO_SERVICES_FAIL';

export const WORKER_APPLY_CREATE_REQUEST = 'WORKER_APPLY_CREATE_REQUEST';
export const WORKER_APPLY_CREATE_SUCCESS = 'WORKER_APPLY_CREATE_SUCCESS';
export const WORKER_APPLY_CREATE_FAIL = 'WORKER_APPLY_CREATE_FAIL';

export const GET_WORKER_APPLY_ALL_RESUME_REQUEST = 'GET_WORKER_APPLY_ALL_RESUME_REQUEST';
export const GET_WORKER_APPLY_ALL_RESUME_SUCCESS = 'GET_WORKER_APPLY_ALL_RESUME_SUCCESS';
export const GET_WORKER_APPLY_ALL_RESUME_FAIL = 'GET_WORKER_APPLY_ALL_RESUME_FAIL';
export const GET_WORKER_APPLY_SINGLE_RESUME_REQUEST = 'GET_WORKER_APPLY_SINGLE_RESUME_REQUEST';
export const GET_WORKER_APPLY_SINGLE_RESUME_SUCCESS = 'GET_WORKER_APPLY_SINGLE_RESUME_SUCCESS';
export const GET_WORKER_APPLY_SINGLE_RESUME_FAIL = 'GET_WORKER_APPLY_SINGLE_RESUME_FAIL';
export const DELETE_WORKER_RESUME_ESUME_REQUEST = 'DELETE_WORKER_RESUME_ESUME_REQUEST';
export const DELETE_WORKER_RESUME_ESUME_SUCCESS = 'DELETE_WORKER_RESUME_ESUME_SUCCESS';
export const DELETE_WORKER_RESUME_ESUME_FAIL = 'DELETE_WORKER_RESUME_ESUME_FAIL';

export const WORKER_APPLY_RESET = 'WORKER_APPLY_RESET';

export const WORKER_RESUME_ARUP_REQUEST = 'WORKER_RESUME_ARUP_REQUEST';
export const WORKER_RESUME_ARUP_SUCCESS = 'WORKER_RESUME_ARUP_SUCCESS';
export const WORKER_RESUME_ARUP_FAIL = 'WORKER_RESUME_ARUP_FAIL';

